# .pre-commit-config.yaml - Hooks de pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix']

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length=120]
        files: ^badg3rfuzz\.py$
        exclude: ^(tests/|logs/|htmlcov/|.benchmarks/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
        files: ^badg3rfuzz\.py$
        exclude: ^(tests/|logs/|htmlcov/|.benchmarks/)

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --extend-ignore=E203,W503]
        files: ^badg3rfuzz\.py$
        exclude: ^(tests/|logs/|htmlcov/|.benchmarks/)

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-r", "badg3rfuzz.py", "-f", "json", "-o", "bandit-report.json"]
        exclude: ^(tests/|logs/|htmlcov/|.benchmarks/)

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest-unit
        entry: pytest
        language: system
        args: [tests/, -v, --tb=short, -m, "not integration and not security"]
        pass_filenames: false
        always_run: true